Initial configuration of repo
dirac-institute/sorcha_community_utils pull request #1
Opened 2023-07-31 23:47 UTC by drewoldag

Applying the LINCC frameworks Python project template
Added `SinusoidalLightcurve` source, test, simple notebook and documentation page
Provided scaffolding for additional documentation as well as placeholder documentation to be filled later.

2023-07-31 23:50 UTC, drewoldag commented
Note that the CI will initially fail because the version of `sorcha` that is available on PyPI needs to be updated. Once this PR (https://github.com/dirac-institute/sorcha/pull/493) is merged, we should be in a good place to increment the version number and then the CI here will pass. 

Testing was performed locally using `sorcha` installed from github with pip. (Not what we would want in production)

2023-08-01 09:26 UTC, mschwamb requested changes

2023-08-01 09:26 UTC, mschwamb commented on src/sorcha_community_utils/sinusoidal/sinusoidal_lightcurve.py
Maybe we're not going to have a lot of classes, but I think it's worth have an lc and activity directory and then you have your different developed classes in there so if I go to activity these are prescriptions for cometary activity and if I go into the lc directory it's prescriptions of rotational light curve effects. 

So I think this should be in lc/sinuisoidal/sinuisoidal_lightcurve.py 

I am definitely open to other suggestions.

2023-08-01 09:26 UTC, mschwamb commented on tests/sinusoidal/test_sinusoidal.py
Same thing as above. Should the tests also be split by light curve and activity?

2023-08-01 13:59 UTC, drewoldag commented on src/sorcha_community_utils/sinusoidal/sinusoidal_lightcurve.py
I'm up for extra organizing, so this is no problem to implement.

2023-08-01 20:02 UTC, mschwamb approved these changes

2023-08-01 21:22 UTC, merged